apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lubo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lubo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lubo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lubo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lubo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pxsl-tenant/rhtap-demo-app/hacbs-test-project-lubo@sha256:cb71b6c2b1c60189cda8d0e70dc1ca6801086bc5c998ec640e456b8c0a0ec572
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
